### ISSUE TITLE
New Issue To Be solved

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1111]
Something to do.

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
